---
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: yeti
    css: "style.css"
    source_code: "https://github.com/easystats/dashboard"
params:
  title:
    label: Title of report
    value: Easystats dashboard
    input: text
  dashboard_start: 
    label: Start date of report
    value: !r lubridate::today() - lubridate::ddays(90)
    input: date
  orgs:
    label: GitHub organizations
    value: easystats
    input: text
  privacy:
    label: Repository Privacy
    value: PUBLIC
    choices: [PUBLIC, PRIVATE, BOTH]
title: "`r params$title`"	
---

```{r setup, include = FALSE}
# knitr::opts_chunk$set(eval = FALSE, cache = TRUE)

library(cranlogs)
library(htmltools)
library(httr2)
library(flexdashboard)
library(gh)
library(jsonlite)
library(lubridate)
library(dplyr)
library(purrr)
library(tibble)
# remotes::install_github("ThinkR-open/tidyversedashboard", ref = "zero-issues")
library(reactable)
library(fontawesome)
library(tidyversedashboard)
library(tidyr)

gh_colors <- list(
  green = "#2cbe4e",
  red = "#CB2434",
  purple = "#6f42c1")
dashboard_start <- params$dashboard_start
dashboard_duration <- format(today() - dashboard_start, format = "%d")
orgs <- scan(text = params$orgs, what = "character", sep = ",", strip.white = TRUE, quiet = TRUE)
privacy <- normalize_privacy(params$privacy)

main_repos <- c("bayestestR", "correlation", "datawizard", "easystats", "effectsize", "insight",
                "modelbased", "parameters", "performance", "report", "see")

```

```{r remaining, message=FALSE}
#' Wait if required rate is above remaining one
#'
#' @param required Required amount of points you need for the next step
#' When using the built-in GITHUB_TOKEN in GitHub Actions, the rate limit is 1,000 requests per hour per repository
wait_for_rate <- function(required = 100) {
  
# Rate limit ----
ratelimit <- "query {
  viewer {
    login
  }
  rateLimit {
    limit
    cost
    remaining
    resetAt
  }
}"

rate_value <- gh::gh_gql(ratelimit)

message("Rate value:", rate_value)

  if (rate_value[[1]]$rateLimit$remaining < required) {
    # remaining seconds
    remaining <- round(as.numeric(as.duration(as_datetime(rate_value[[1]]$rateLimit$resetAt) - now())))
    
    message(paste("Let's wait a little", round(remaining/60), "minutes"))
    Sys.sleep(remaining)
  } else {
    message("Rate's good")
  }
}
```


```{r pr_stats, include=FALSE, message=FALSE}
options(repos = c(CRAN='https://cloud.r-project.org'))

wait_for_rate(280)

# Requires ~500 points for rate limitation
pr_data <- tryCatch(
  map_dfr(orgs, org_pr, privacy = privacy),
  error = function(e) message(e$content$errors))

if (!is.null(pr_data)) {
  prs <- pr_data %>% 
    filter(updated >= dashboard_start) %>%
    mutate(reviewer = map2(reviews, comments, function(reviews, comments) unique(c(reviews$reviewer, comments$commenter)))) 
  prs <- prs %>%
    select(owner, repo, issue, author, created, updated, closed, reviewer) %>%
    unnest(cols = c(reviewer)) %>%
    filter(reviewer != author, reviewer != "codecov.io") %>%
    mutate(
      reviewer = github_user_home(reviewer),
      author = github_user_home(author),
      is_closed = !is.na(closed))

  pr_authors <- prs %>% group_by(author, is_closed) %>% select(-reviewer) %>% unique() %>% tally(sort = TRUE)
  pr_reviewers <- prs %>% group_by(reviewer, is_closed) %>% select(-author) %>% unique() %>% tally(sort = TRUE)
  pr_pairs <- prs %>% group_by(author, reviewer, is_closed) %>% tally(sort = TRUE)
} else {
  pr_authors <- NULL
  pr_reviewers <- NULL
  pr_pairs <- NULL
}

# Get remaining rate
wait_for_rate(1)
```


Overview
========

```{r repo_stats, echo = FALSE, message=FALSE}
# Requires ~700 points for rate limitation
wait_for_rate(650)

row_details <- function(index) {
  pkg <- packageDescription(main_repos[index])
  urls <- unlist(strsplit(gsub(",", " , ", pkg$URL[1], perl = TRUE), "[ \n]"))
  pkg$Author <- gsub("\\s*\\([^\\)]+\\)", "", pkg$Author)
  
  pkg_field <- function(name, ...) {
    if (any(is.na(...))) NULL
    else tagList(div(class = "detail-label", name), ...)
  }

  detail <- div(
    class = "package-detail",
    div(class = "detail-header", pkg$Package, span(class = "detail-title", pkg$Title)),
    div(class = "detail-description", pkg$Description),
    pkg_field("Version", pkg$Version),
    pkg_field("Depends", pkg$Depends),
    pkg_field("Imports", pkg$Imports),
    pkg_field("Suggests", pkg$Suggests),
    pkg_field("Author", pkg$Author),
    pkg_field("License", pkg$License),
    pkg_field("URL", lapply(urls, function(url) {
      if (grepl("https?://", url)) tags$a(href = url, url)
      else if (identical(url, ",")) ", "
      else url
    })),
    pkg_field("Last Built", pkg$Built),
  )

  detail
}

repo_data <- map(orgs, org_data, privacy)

repo_summary <- map_dfr(repo_data, "summary") %>% 
  distinct(owner, repo, .keep_all = TRUE) %>% 
  filter(tolower(owner) %in% tolower(orgs), repo %in% main_repos) %>%
  select(-owner, -description, -p1, -features, -bugs, -unlabeled)

downloads <- cran_downloads(when = "last-week", packages = unique(repo_summary$repo)) %>% 
  group_by(package) %>% 
  mutate(downloads_last_week = sum(count)) %>% 
  ungroup() %>% 
  select(package, downloads_last_week) %>% 
  distinct()

coverage <- data.frame(
  repo = repo_summary$repo,
  coverage_badge = coverage_status_badge("easystats", repo_summary$repo),
  check_badge = github_status_badge("easystats", repo_summary$repo)
)

change_check_badge <- c("correlation", "datawizard", "easystats", "effectsize", "insight",
                        "parameters", "performance", "report", "see")

repo_summary <- left_join(repo_summary, downloads, by = c("repo" = "package")) %>% 
  left_join(coverage, by = "repo") %>% 
  select(repo, default_branch, watchers, open_issues, prs, everything()) %>% 
  rename(
    Repository = repo,
    "Main branch" = default_branch,
    "Open PRs" = prs,
    Stars = watchers,
    "Open issues" = open_issues,
    "Downloads last week" = downloads_last_week,
    Coverage = coverage_badge,
    `R CMD check` = check_badge
  ) %>% 
  mutate(
    Coverage = ifelse(`Main branch` == "master", gsub("main", "master", Coverage), Coverage),
    `R CMD check` = ifelse(Repository %in% change_check_badge, gsub("R-CMD-CHECK|R-CMD-check", "R-check", `R CMD check`), `R CMD check`)
  ) %>% 
  arrange(Repository)

reactable(
  repo_summary,
  defaultPageSize = nrow(repo_summary),
  columns = list(
    `Downloads last week` = colDef(
      format = colFormat(separators = TRUE)
    ),
    Coverage = colDef(
      html = TRUE,
      cell = JS("function(cellInfo) {
        return cellInfo.value
      }")
    ),
    `R CMD check` = colDef(
      html = TRUE,
      cell = JS("function(cellInfo) {
        return cellInfo.value
      }")
    )
  ),
  details = row_details,
  theme = reactableTheme(
    headerStyle = list(
      "&:hover[aria-sort]" = list(background = "hsl(0, 0%, 96%)"),
      "&[aria-sort='ascending'], &[aria-sort='descending']" = list(background = "hsl(0, 0%, 96%)"),
      borderColor = "#555"
    ),
    style = list(
      fontFamily = "Work Sans, Helvetica Neue, Helvetica, Arial, sans-serif",
      fontSize = "1.25rem",
      "a" = list(
        color = "#000000",
        textDecoration = "none",
        "&:hover, &:focus" = list(
          textDecoration = "underline",
          textDecorationThickness = "1px"
        )
      ),
      ".number" = list(
        color = "#666666",
        fontFamily = "Source Code Pro, Consolas, Monaco, monospace"
      ),
      ".tag" = list(
        padding = "0.125rem 0.25rem",
        color = "hsl(0, 0%, 40%)",
        fontSize = "1.25rem",
        border = "1px solid hsl(0, 0%, 24%)",
        borderRadius = "2px",
        textTransform = "uppercase"
      )
    )
  ),
  class = "packages-table"
)

```


Open issues
===========
```{r issue_summary}
substitute_emoji <- function(x) {
  m <- gregexpr(":[^[:space:]]+:", x)

  regmatches(x, m) <- lapply(regmatches(x, m), function(xx) map_chr(gsub(":", "", xx), purrr::possibly(emo::ji, "")))
  x
}

issues <- map_dfr(repo_data, "issues") %>%
  distinct(owner, repo, issue, .keep_all = TRUE) %>%
  filter(tolower(owner) %in% tolower(orgs))

# linkify the titles, and replace emoji
issue_table <- issues %>%
  mutate(
    title = glue::glue('<a rel="noopener" target="_blank" href="https://github.com/{owner}/{repo}/issues/{issue}">{title}</a>'),
    # Modify issue after title
    issue = glue::glue('<a rel="noopener" target="_blank" href="https://github.com/{owner}/{repo}/issues/{issue}">{issue}</a>'),
    labels = substitute_emoji(map_chr(labels, paste, collapse = ", "))
  ) %>%
  select(-owner) %>% 
  rename(
    Repository = repo,
    Issue = issue,
    Title = title,
    Updated = updated
  ) %>% 
  select(-p1)

reactable(
  issue_table,
  searchable = TRUE,
  pagination = FALSE, 
  highlight = TRUE,
  filterable = TRUE,
  columns = list(
    Issue = colDef(html = TRUE),
    Title = colDef(html = TRUE)
  ),
  theme = reactableTheme(
    headerStyle = list(
      "&:hover[aria-sort]" = list(background = "hsl(0, 0%, 96%)"),
      "&[aria-sort='ascending'], &[aria-sort='descending']" = list(background = "hsl(0, 0%, 96%)"),
      borderColor = "#555"
    ),
    style = list(
      fontFamily = "Work Sans, Helvetica Neue, Helvetica, Arial, sans-serif",
      fontSize = "1.25rem",
      "a" = list(
        color = "#000000",
        textDecoration = "none",
        "&:hover, &:focus" = list(
          textDecoration = "underline",
          textDecorationThickness = "1px"
        )
      ),
      ".number" = list(
        color = "#666666",
        fontFamily = "Source Code Pro, Consolas, Monaco, monospace"
      ),
      ".tag" = list(
        padding = "0.125rem 0.25rem",
        color = "hsl(0, 0%, 40%)",
        fontSize = "1.25rem",
        border = "1px solid hsl(0, 0%, 24%)",
        borderRadius = "2px",
        textTransform = "uppercase"
      )
    )
  )
)
```

